apiVersion: apps/v1
kind: Service
metadata:
  name: udagram-feed-svc
  labels:
    app: udagram-feed-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed-svc
  template:
    metadata:
      labels:
        app: udagram-feed-svc
    spec:
      containers:
      - name: udagram-feed-service-container
        image: nowindi/udagram-feed-service-container
        ports:
        - containerPort: 8080


        
